'use client'; // تأكد من وجود هذا السطر في بداية الملف

import localFont from "next/font/local";
import "./globals.css";
import Navbar from "./Navbar/page";
import Footer from "./Footer/page";
import { useEffect } from 'react';
import { useRouter } from 'next/navigation'
import "../../node_modules/@fortawesome/fontawesome-svg-core";
import { Toaster } from "react-hot-toast";
import { store } from './lib/store'
import { Provider } from 'react-redux'

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };
export default function RootLayout({ children }) {
  const router = useRouter()
useEffect(() => {
  const token = localStorage.getItem("token"); // الحصول على token من localStorage
  // تحقق من وجود token
  if (!token) {
    router.push('/login'); // توجيه المستخدم إلى صفحة تسجيل الدخول إذا لم يكن موجودًا
  }
}, [router]); // تأكد من إضافة router كاعتماد
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable}`}
        style={{
          display: "flex",
          flexDirection: "column",
          minHeight: "100vh",
          justifyContent: "space-between",
        }}
      >
        <Provider store={store}>
        <Navbar />
        <main style={{ flexGrow: 1 }}>{children}</main>
        <Footer />
        </Provider>
        <Toaster />
      </body>
    </html>
  );
}
